on: push
name: Octicons Build
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: '10.x'
      - name: Version
        uses: ./.github/actions/version
      - run: npm install
      - run: npm run build
      - run: cp -r icons lib/build/svg
      - run: npm run lint
      - run: npm test
      - uses: actions/upload-artifact@master
        with:
          name: octicons
          path: ./lib/build
  gem:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@master
      - name: Version
        uses: ./.github/actions/version
      - uses: actions/download-artifact@master
        with:
          name: octicons
          path: ./lib/build
      - uses: ./.github/actions/build_ruby
        env:
          RUBYGEMS_TOKEN: ${{ secrets.RUBYGEMS_TOKEN }}
        with:
          args: octicons_gem
      - run: ls ./lib/octicons_gem/pkg
      - uses: actions/upload-artifact@master
        with:
          name: octicons_gem
          path: ./lib/octicons_gem/pkg
  helper:
    runs-on: ubuntu-latest
    needs: gem
    steps:
      - uses: actions/checkout@master
      - name: Version
        uses: ./.github/actions/version
      - uses: actions/download-artifact@master
        with:
          name: octicons
          path: ./lib/build
      - uses: actions/download-artifact@master
        with:
          name: octicons_gem
          path: ./lib/octicons_helper/vendor/cache
      - uses: ./.github/actions/build_ruby
        env:
          RUBYGEMS_TOKEN: ${{ secrets.RUBYGEMS_TOKEN }}
        with:
          args: octicons_helper
  jekyll:
    runs-on: ubuntu-latest
    needs: gem
    steps:
      - uses: actions/checkout@master
      - name: Version
        uses: ./.github/actions/version
      - uses: actions/download-artifact@master
        with:
          name: octicons
          path: ./lib/build
      - uses: actions/download-artifact@master
        with:
          name: octicons_gem
          path: ./lib/octicons_jekyll/vendor/cache
      - uses: ./.github/actions/build_ruby
        env:
          RUBYGEMS_TOKEN: ${{ secrets.RUBYGEMS_TOKEN }}
        with:
          args: octicons_jekyll
  node:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@master
      - name: Version
        uses: ./.github/actions/version
      - uses: actions/download-artifact@master
        with:
          name: octicons
          path: ./lib/build
      - uses: ./.github/actions/build_node
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
        with:
          args: octicons_node
  react:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@master
      - name: Version
        uses: ./.github/actions/version
      - uses: actions/download-artifact@master
        with:
          name: octicons
          path: ./lib/build
      - uses: ./.github/actions/build_node
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
        with:
          args: octicons_react
