## Jekyll configs
markdown: GFM
permalink: /:year/:month/:day/:title/
highlighter: rouge
sass:
  style: :compressed
gems:
  - jekyll-sitemap

## Site structure
collections:
  testimonials:
    output: true
    permalink: /testimonials/:title/
  sections:
    output: false
    permalink: /:title/

defaults:
  -
    scope:
      path: ""
      type: "testimonials"
    values:
      layout: "testimonial"

## Basic company info
title: Company
primary_author: "Company, Inc."
shortname: Comp
tagline: "Serving ours customers' needs"
offering: "Business and corporate services"
offer_description: "We do a lot of stuff. This is a lengthy paragraph of text."

## Site and contact bits
baseurl: "https://shelbybrad.com"
# subpath should include leading slash or be an empty string
subpath: ''
source_repo: https://www.github.com/shelbybrad/shelbybrad.github.io
email: ao5357@gmail.com 
phone: (248) 721-0350
phonedigits: "2487210350"
# gaid: UA-697953-3

## schema.org type (default for site, often "Website")
schema: Website

## Open Graph
og_street_address: 1428 Mark Ave
og_locality: Lincoln Park
og_region: MI
og_postal_code: "48146"
og_country: USA

## Social links
social:
  -
    title: Facebook
    url: https://www.facebook.com/bradczerniak
  -
    title: Twitter
    url: https://twitter.com/ao5357

## Colors
# Secondary especially should not be a regular blue
# Text should be close to black, but not black (or dark gray)
# Light is typically #fff, but could be a non-white very light tint
colors:
  primary: "#014"
  secondary: "#f41"
  tertiary: "#7c1"
  quarternary: "#04f"
  text: "#002"
  light: "#fff"
