## Jekyll configs
markdown: GFM
theme: jekyll-theme-primer
permalink: /blog/:title/
highlighter: rouge
collections_dir: collections
sass:
  sass_dir: assets/css
  style: :compressed
plugins:
  - jekyll-sitemap

## Site structure
collections:
  docs:
    output: true
    permalink: /docs/:path/
  events:
    output: true
    permalink: /events/:path/
  sections:
    output: false
    permalink: /:title/

defaults:
  -
    scope:
      path: ""
      type: "docs"
    values:
      layout: "doc"
  -
    scope:
      path: ""
      type: "events"
    values:
      layout: "event"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "sections"
    values:
      layout: "section"

## Basic company info
title: "Shelby and Brad"
primary_author: "Brad Czerniak"
shortname: brelby
tagline: "Serving ours customers' needs"
offering: "Business and corporate services"
offer_description: "We do a lot of stuff. This is a lengthy paragraph of text."

## Site and contact bits
source_repo: https://www.github.com/shelbybrad/shelbybrad.github.io
email: ao5357@gmail.com
phone: (248) 721-0350
phonedigits: "2487210350"
# gaid: UA-697953-3

## schema.org type (default for site, often "Website")
schema: Website

## Open Graph
og_street_address: 1428 Mark Ave
og_locality: Lincoln Park
og_region: MI
og_postal_code: "48146"
og_country: USA

## PWA and other SEO
background_color: "#fff"
theme_color: "#003f80"

## Social links
social:
  -
    title: Facebook
    url: https://www.facebook.com/bradczerniak
  -
    title: Twitter
    url: https://twitter.com/ao5357
