####
## @file
## Jekyll configuration
##
## We try to push as much sitewide config as possible into this file, so a new deployment can be going through this one
## place and changing values here and there.
##
## When adding new sections, be sure to name them so they make sense to others, and to document with good comments
## wherever possible/practical.
####

## Basic site info
title: "Shelby and Brad"
primary_author: "Brad Czerniak"
shortname: brelby
tagline: "Serving ours customers' needs"
offering: "Business and corporate services"
offer_description: "We do a lot of stuff. This is a lengthy paragraph of text."

## Site and contact bits
source_repo: https://www.github.com/shelbybrad/shelbybrad.github.io
email: ao5357@gmail.com
phone: (248) 721-0350
phonedigits: "2487210350"
# gaid: UA-697953-3

## schema.org type (default for site, often "Website")
schema: Website

## Open Graph (appears in footer for schema.org too)
open_graph:
  og_street_address: 1428 Mark Ave
  og_locality: Lincoln Park
  og_region: MI
  og_postal_code: "48146"
  og_country: USA

## PWA and other SEO
manifest_webmanifest:
  background_color: "#fff"
  theme_color: "#003f80"

## Social links
social:
  - title: Facebook
    url: https://www.facebook.com/bradczerniak
  - title: Twitter
    url: https://twitter.com/ao5357

## The 'THANKS' and 'SITE' sections of humans.txt
## (Note: the 'TEAM' section is built from the content in the _people collection
humans_txt:
  site:
    - key: "Components"
      value: "property--value"
    - key: "Language"
      value: "English"
    - key: "Doctype"
      value: "HTML5"
    - key: "IDE"
      value: "PhpStorm, Sublime Text"
    - key: "Software"
      value: "Jekyll"
    - key: "Standards"
      value: "CSS3, ES6, HTML5, WCAG 2.1"
  thanks:
    - name: "Brad Czerniak"
      job_title: "finished-starter"
      contact: "ao5357 [at] gmail.com"
      twitter: "@ao5357"
      from: "Lincoln Park, Michigan, USA"

## CSS Custom Properties at the :root
css:
  root:
    - key: "--color--black" # Monochrome colors
      value: "#222"
    - key: "--color--grey-dark"
      value: "#555"
    - key: "--color--grey"
      value: "#999"
    - key: "--color--grey-light"
      value: "#eee"
    - key: "--color--white"
      value: "#fff"
    - key: "--color--main" # Theme colors
      value: "#4074a0"
    - key: "--color--main-dark"
      value: "#1d3141"
    - key: "--color--main-light"
      value: "#74c2ff"
    - key: "--color--second"
      value: "#a0781f"
    - key: "--color--second-dark"
      value: "#41201c"
    - key: "--color--second-light"
      value: "#ffc227"
    - key: "--color--third"
      value: "#73a040"
    - key: "--color--third-dark"
      value: "#204120"
    - key: "--color--third-light"
      value: "#b7ff61"
    - key: "--color--accent" # UI colors
      value: "#6d40a0"
    - key: "--color--status"
      value: "#004085"
    - key: "--color--status-background"
      value: "#cce5ff"
    - key: "--color--warning"
      value: "#856404"
    - key: "--color--warning-background"
      value: "#fff3cd"
    - key: "--color--error"
      value: "#721c24"
    - key: "--color--error-background"
      value: "#f8d7da"
    - key: "--color--street-sign--glow" # Additional colors
      value: "#b062ff"
    - key: "--color--street-sign--peach"
      value: "#fad295"
    - key: "--color--street-sign--red"
      value: "#a01022"
    - key: "--color--street-sign--red-dark"
      value: "#410e18"
    - key: "--color--street-sign--red-light"
      value: "#ff808a"
    - key: "--font-family--input" # Fonts
      value: "'Lato'"
    - key: "--font-family--monospace"
      value: "'courier new'"
    - key: "--font-family--primary"
      value: "'Lato'"
    - key: "--font-family--secondary"
      value: "'Engagement'"
    - key: "--line-height--default" # Typography, spacing, and layout
      value: "1.425"
    - key: "--line-height--heading"
      value: "1"
    - key: "--layout--content-area"
      value: "1080px"
    - key: "--spacing--single"
      value: "0.625rem"

## Jekyll configs
collections_dir: collections
encoding: utf-8
exclude:
  - CNAME
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - node_modules
  - readme.md
  - "vendor/bundle/"
  - "vendor/cache/"
  - "vendor/gems/"
  - "vendor/ruby/"
future: true
highlighter: rouge
include:
  - ".htaccess"
keep_files:
  - ".git"
  - ".svn"
kramdown:
  auto_ids: true
  entity_output: as_char
  footnote_nr: 1
  hard_wrap: false
  input: GFM
  show_warnings: false
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  toc_levels: [1, 2, 3, 4, 5, 6]
markdown: kramdown
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
paginate_path: /page-:num
permalink: /blog/:title/
plugins:
  - jekyll-sitemap
safe: false
sass:
  sass_dir: assets/css
  style: :compressed
strict_front_matter: false
theme: jekyll-theme-primer
timezone: Etc/UTC # Allows use to set dates/times without a GMT offset.
unpublished: false

## Site structure
collections:
  docs:
    output: true
    permalink: /docs/:path/
  events:
    output: true
    permalink: /events/:path/
  people:
    output: true
    permalink: /people/:path/
  sections:
    output: false
    permalink: /:title/

defaults:
  - scope:
      path: ""
      type: "docs"
    values:
      layout: "doc"
  - scope:
      path: ""
      type: "events"
    values:
      layout: "event"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "people"
    values:
      layout: "person"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "sections"
    values:
      layout: "section"
